config/routes.rb
Rails.application.routes.draw do
  resources :guards
  resources :appointments
  resources :workers
  resources :worker_types
  resources :medical_centers
  resources :medical_center_types
  resources :ensayos
  devise_for :users

  root to: 'ensayos#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ensayo.rb
class Ensayo < ApplicationRecord
  paginates_per 4
end

app/controllers/ensayos_controller.rb
class EnsayosController < ApplicationController
  before_action :set_ensayo, only: %i[ show edit update destroy ]

  # GET /ensayos or /ensayos.json
  def index
    @ensayos = Ensayo.all
    @ensayos = @ensayos.order(:name).page(params[:page] || 1)
  end

  # GET /ensayos/1 or /ensayos/1.json
  def show
  end

  # GET /ensayos/new
  def new
    @ensayo = Ensayo.new
  end

  # GET /ensayos/1/edit
  def edit
  end

  # POST /ensayos or /ensayos.json
  def create
    @ensayo = Ensayo.new(ensayo_params)

    respond_to do |format|
      if @ensayo.save
        format.html { redirect_to @ensayo, notice: "Ensayo was successfully created." }
        format.json { render :show, status: :created, location: @ensayo }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ensayo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ensayos/1 or /ensayos/1.json
  def update
    respond_to do |format|
      if @ensayo.update(ensayo_params)
        format.html { redirect_to @ensayo, notice: "Ensayo was successfully updated." }
        format.json { render :show, status: :ok, location: @ensayo }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ensayo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ensayos/1 or /ensayos/1.json
  def destroy
    @ensayo.destroy
    respond_to do |format|
      format.html { redirect_to ensayos_url, notice: "Ensayo was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ensayo
      @ensayo = Ensayo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ensayo_params
      params.require(:ensayo).permit(:name)
    end
end

app/helpers/ensayos_helper.rb
module EnsayosHelper
end

app/views/ensayos/_form.html.erb
<%= form_with(model: ensayo) do |form| %>
  <% if ensayo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ensayo.errors.count, "error") %> prohibited this ensayo from being saved:</h2>

      <ul>
        <% ensayo.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/ensayos/edit.html.erb
<h1>Editing Ensayo</h1>

<%= render 'form', ensayo: @ensayo %>

<%= link_to 'Show', @ensayo %> |
<%= link_to 'Back', ensayos_path %>

app/views/ensayos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ensayos</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ensayos.each do |ensayo| %>
      <tr>
        <td><%= ensayo.name %></td>
        <td><%= link_to 'Show', ensayo %></td>
        <td><%= link_to 'Edit', edit_ensayo_path(ensayo) %></td>
        <td><%= link_to 'Destroy', ensayo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @ensayos %>
<br>
<li class="nav-item">
    <%= link_to 'New Ensayo', new_ensayo_path if can? :create, Ensayo%>
  </li

app/views/ensayos/new.html.erb
<h1>New Ensayo</h1>

<%= render 'form', ensayo: @ensayo %>

<%= link_to 'Back', ensayos_path %>

app/views/ensayos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @ensayo.name %>
</p>

<%= link_to 'Edit', edit_ensayo_path(@ensayo) %> |
<%= link_to 'Back', ensayos_path %>